"""
ex12_abaqus_inp_plate_fold.py
=============================
Runs a 90-degree folding simulation by reading all parameters, mesh,
materials, rigid bodies, tie constraints, and boundary conditions
directly from an Abaqus input deck (.inp) file.
"""

import os
import time
import numpy as np
from dispsolver.io import read_abaqus_input
from dispsolver.solver import DynamicSolver
from dispsolver.solver.dt_controller import AdaptiveDtController
from dispsolver.export.plotter import plot_and_save_deformed_shape_png
from dispsolver.postprocess import LayerSlipTracker, ResultWriter


def _laminate_layer_materials(mesh, material_names, max_node_id=10000):
    """Material name of each display layer, bottom -> top.

    Derived from the mesh rather than hard-coded so the table stays
    correct if gen_ex12_inp.py's layup changes: each element is bucketed
    by its centroid height, and each layer takes the *MATERIAL name of
    the pid its elements carry.
    """
    ys = sorted({round(float(n.y), 6) for nid, n in mesh.nodes.items()
                 if nid < max_node_id})
    if len(ys) < 2:
        return None
    mid_to_layer = {}
    for j in range(len(ys) - 1):
        mid_to_layer[round(0.5 * (ys[j] + ys[j + 1]), 6)] = j

    layers = [None] * (len(ys) - 1)
    for elem in mesh.elements.values():
        if any(nid >= max_node_id for nid in elem.node_ids):
            continue
        yc = round(float(np.mean([mesh.nodes[n].y for n in elem.node_ids])), 6)
        j = mid_to_layer.get(yc)
        if j is not None and layers[j] is None:
            layers[j] = material_names.get(elem.pid, f"pid{elem.pid}")
    return [m or "?" for m in layers]

def run_abaqus_inp_folding(inp_path: str = None, before_png_name: str = "ex12_before_folding_shape.png",
                            after_png_name: str = "ex12_final_folding_shape.png",
                            result_name: str = "ex12_result.pkl"):
    """Run the folding solve from a given .inp deck.

    `inp_path` defaults to the standard ex12 deck (generated by
    gen_ex12_inp.py) but can be pointed at any other .inp -- e.g.
    ex13_unified_model_io.py's `roundtrip` mode passes a temp file built
    in-memory from the same generator, to prove generate()+read_abaqus_input
    round-trip consistently without duplicating this whole solve loop.
    """
    print("=" * 100)
    print(" EX12: 90-Degree Display Folding Directly from Abaqus .inp File")
    print("=" * 100)

    if inp_path is None:
        inp_path = os.path.join(os.path.dirname(__file__), "ex12_rigid_plate_display_fold.inp")
    if not os.path.exists(inp_path):
        raise FileNotFoundError(f"Input file not found at {inp_path}. Run gen_ex12_inp.py first.")

    print(f"Reading Abaqus input deck: {inp_path}")
    result = read_abaqus_input(inp_path)
    print(f"Parsed result: {result}")

    return run_folding_from_result(result, before_png_name, after_png_name,
                                   case_name=os.path.basename(inp_path),
                                   result_name=result_name)


def run_folding_from_result(result, before_png_name: str = "ex12_before_folding_shape.png",
                             after_png_name: str = "ex12_final_folding_shape.png",
                             case_name: str = "in-memory",
                             result_name: str = "ex12_result.pkl",
                             max_steps: int = None):
    """Shared solve loop, driven by any object exposing the same fields as
    `dispsolver.io.model_builder.ModelBuilderResult` (`.mesh`, `.materials`,
    `.material_params`, `.solver_config`, `.rbe2_constraints`,
    `.penalty_constraints`, `.rbe2_elements`, `.boundaries`).

    `run_abaqus_inp_folding` builds this via `read_abaqus_input`;
    `ex13_unified_model_io.py`'s `build` mode constructs an equivalent
    result directly as Python objects (no .inp text at all) and calls
    this function directly, so all three model sources (read/roundtrip/
    build) drive the exact same solve loop with no duplication.
    """
    mesh = result.mesh
    nid_to_idx = mesh.node_id_to_index()

    # Adjust rigid plate material parameters to virtually zero stiffness
    # to avoid spurious stresses from finite rotations of linear Q4 elements.
    for pid, params in result.material_params.items():
        if params.get("E", 0.0) > 10000.0:
            print(f"Adjusting plate material (pid={pid}) Young's modulus from {params['E']} to 1e-6 to eliminate spurious stresses.")
            params["E"] = 1e-6
            
    for tc in result.penalty_constraints:
        print(f"Adjusting tie constraint ({tc.name}) penalty stiffness from {tc.k_tie} to 1e4.")
        tc.k_tie = 1e4

    # ------------------------------------------------------------------
    # 1. Process boundary conditions from .inp
    # ------------------------------------------------------------------
    translation_bc_dofs = []
    translation_bc_vals = []
    prescribed_rotations = {}  # master_node_id -> prescribed_theta_value

    for bc in result.boundaries:
        # Resolve node IDs for the boundary condition
        # (could be a node ID string like "10000" or a set name)
        try:
            node_id = int(bc.nset)
            node_ids = [node_id]
        except ValueError:
            ns = mesh.node_sets.get(bc.nset)
            if ns:
                node_ids = list(ns.node_ids)
            else:
                continue

        # Check DOFs
        for nid in node_ids:
            n_idx = nid_to_idx[nid]
            for dof_num in range(bc.dof1, bc.dof2 + 1):
                if dof_num in (1, 2):
                    # Translation DOFs (1=UX, 2=UY)
                    dof_idx = n_idx * 2 + (dof_num - 1)
                    translation_bc_dofs.append(dof_idx)
                    translation_bc_vals.append(bc.value)
                elif dof_num in (3, 6):
                    # Rotation DOF (3 in 2D, 6 in 3D)
                    prescribed_rotations[nid] = bc.value

    print(f"Found translation boundary conditions on {len(translation_bc_dofs)} DOFs.")
    print(f"Found prescribed rotations on master nodes: {prescribed_rotations}")

    # ------------------------------------------------------------------
    # 2. Setup Solver
    # ------------------------------------------------------------------
    # We use exact kinematic condensation for rigid plate movement
    solver = DynamicSolver(
        mesh=mesh,
        material=result.materials,
        material_params=result.material_params,
        rho=result.solver_config.get("density", 1e-9),
        mode="quasistatic",
        tol=1e-3,
        rtol=1e-4,
        atol=1e-6,
        max_iter=25,
        element_type={1: "Q4_COROTATIONAL", 2: "Q4_VISCO_SIMO"},
        rbe2_constraints=result.rbe2_constraints,
        penalty_constraints=result.penalty_constraints,
        ul_mode=True,
        alpha=-0.15,
        verbose=True,
    )

    solver.theta_penalty_k = 1e8

    # Set translation boundaries
    if translation_bc_dofs:
        solver.set_prescribed_dofs(
            np.array(translation_bc_dofs, dtype=np.int32),
            bc_vals=np.array(translation_bc_vals, dtype=np.float64)
        )

    # ------------------------------------------------------------------
    # 3. Time Stepping Loop
    # ------------------------------------------------------------------
    t_total = result.solver_config.get("t_total", 1.0)
    dt_init = result.solver_config.get("dt_init", 0.005)
    dt_max = result.solver_config.get("dt_max", 0.01)
    dt_min = result.solver_config.get("dt_min", 1e-5)

    dt_ctrl = AdaptiveDtController(dt_init=dt_init, dt_min=dt_min, dt_max=dt_max, target_iters=5)
    t_start_total = time.time()
    step = 0

    # Record every converged increment so the finished run can be
    # re-analyzed/animated without re-solving (~5 min), and track the
    # per-layer tip slip that the soft PSA rows exist to produce.
    layer_materials = _laminate_layer_materials(
        mesh, getattr(result, "material_names", {}) or {}
    )
    writer = ResultWriter(
        mesh,
        materials=result.material_params,
        constraints={"ties": [getattr(tc, "name", "") for tc in result.penalty_constraints],
                     "rbe2_masters": [c.master_id for c in result.rbe2_constraints]},
        meta={"case": case_name, "t_total": t_total,
              "theta_targets_rad": prescribed_rotations,
              "layer_materials": layer_materials},
    )
    slip_tracker = LayerSlipTracker(
        mesh, probe_x=(-40.0, 40.0), layer_materials=layer_materials,
    )

    while solver.time < t_total - 1e-10:
        if max_steps is not None and step >= max_steps:
            # Early stop for profiling/smoke runs. Unlike shrinking
            # t_total this leaves the angle ramp untouched, so the steps
            # taken are the same ones a full run would take.
            print(f"  [MAX STEPS] stopping after {step} steps as requested.")
            break
        dt = dt_ctrl.dt
        if solver.time + dt > t_total:
            dt = t_total - solver.time

        t_next = solver.time + dt
        ratio = t_next / t_total

        # Prescribe current step rotation values proportionally via theta_targets
        targets = {}
        for idx, rbe_con in enumerate(result.rbe2_constraints):
            m_id = rbe_con.master_id
            if m_id in prescribed_rotations:
                theta_target = prescribed_rotations[m_id]
                targets[idx] = theta_target * ratio
        solver.theta_targets = targets

        print("-" * 100)
        print(f"Step {step + 1} | Attempting time increment: dt = {dt:.5f}s (t: {solver.time:.4f}s -> {t_next:.4f}s)")
        print("-" * 100)

        # Solve step
        conv_code = solver.solve_step(dt)

        if conv_code >= 0:
            # Step converged
            solver.time = t_next
            step += 1
            # Log current angles from u_extra
            n_extra_regular = solver.n_extra - len(result.rbe2_constraints)
            angles = [np.degrees(solver.u_extra[n_extra_regular + idx]) for idx in range(len(result.rbe2_constraints))]
            print(f"\n  STEP {step:2d} | t={solver.time:.4f}s | dt={dt:.4f}s | Iters={conv_code:2d} | θ={angles} deg | max|u|={np.max(np.abs(solver.u)):.2f}mm\n")

            theta_deg = float(np.mean(np.abs(angles))) if angles else 0.0
            writer.add_step(solver.time, solver.u,
                            scalars={"theta_deg": theta_deg, "dt": dt,
                                     "n_iter": float(conv_code)})
            slip_tracker.record(solver.u, theta_deg=theta_deg, time=solver.time)

            dt = dt_ctrl.update(n_iter=conv_code, converged=True)
        else:
            # Cutback
            dt = dt_ctrl.update(n_iter=25, converged=False)
            if dt <= dt_ctrl.dt_min:
                # AdaptiveDtController.update() clips dt to exactly dt_min
                # (np.clip), so it never goes strictly below it -- a `<`
                # check here would never fire and the run would cutback
                # forever at the floor instead of aborting cleanly.
                print("FATAL: Time increment below minimum tolerance. Simulation aborted.")
                break
            print(f"  *** STEP {step+1} FAILED (conv={conv_code}). Cutting back dt to {dt_ctrl.dt:.5f}s ***\n")

    t_elapsed = time.time() - t_start_total
    reached_target = solver.time >= t_total - 1e-10
    print("=" * 100)
    if reached_target:
        print(f" SUCCESS: 90-degree display folding simulation completed in {t_elapsed:.2f}s!")
    else:
        print(" FAILED: Simulation did not reach target time.")
    print("=" * 100)

    # ------------------------------------------------------------------
    # 4. Persist the run and report interlayer shear
    #
    # Runs on BOTH exit paths on purpose: a run that stalled at 40 deg is
    # exactly the one whose history you want to inspect, and re-solving to
    # get it back costs ~5 minutes.
    # ------------------------------------------------------------------
    writer.update_meta(reached_target=reached_target, wall_seconds=t_elapsed,
                       n_steps=writer.n_steps, final_time=solver.time)
    for name, arr in slip_tracker.history().items():
        writer.add_array(f"slip__{name}", arr)
    result_path = os.path.join(os.path.dirname(__file__), result_name)
    writer.save(result_path)
    print(f"Saved result ({writer.n_steps} steps) for re-analysis: {result_path}")
    print(f"  reload with: "
          f"from dispsolver.postprocess import load_result; "
          f"r = load_result(r'{result_path}')")

    print(slip_tracker.format_table())
    print()

    # ------------------------------------------------------------------
    # 5. Save before (flat, t=0) / after (final) visualization PNGs
    # ------------------------------------------------------------------
    before_png_path = os.path.join(os.path.dirname(__file__), before_png_name)
    print(f"Saving before (flat) shape visualization to: {before_png_path}")
    plot_and_save_deformed_shape_png(
        mesh=mesh,
        u=np.zeros_like(solver.u),
        tie_constraints=result.penalty_constraints,
        rbe2_elements=result.rbe2_elements,
        save_path=before_png_path
    )

    after_png_path = os.path.join(os.path.dirname(__file__), after_png_name)
    print(f"Saving after (final) shape visualization to: {after_png_path}")
    plot_and_save_deformed_shape_png(
        mesh=mesh,
        u=solver.u,
        tie_constraints=result.penalty_constraints,
        rbe2_elements=result.rbe2_elements,
        save_path=after_png_path
    )
    print("Done.")
    return {
        "solver": solver,
        "result": result,
        "n_nodes": len(mesh.nodes),
        "n_elements": len(mesh.elements),
        "n_rbe2_constraints": len(result.rbe2_constraints),
        "n_penalty_constraints": len(result.penalty_constraints),
        "reached_target": solver.time >= t_total - 1e-10,
    }

if __name__ == "__main__":
    run_abaqus_inp_folding()
