from typing import List, Tuple
import numpy as np
import os

OUTPUT = os.path.join(os.path.dirname(__file__), "ex03_display_fold.inp")


def _mesh():
    """Return (nodes, elements_by_layer, nx) for the 7-layer display panel."""
    xs_left  = np.linspace(-40.0, -15.0, 21)[:-1]
    xs_mid   = np.linspace(-15.0,  15.0, 61)[:-1]
    xs_right = np.linspace( 15.0,  40.0, 21)
    xs = np.concatenate([xs_left, xs_mid, xs_right])
    nx = len(xs)
    ys = np.array([0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35])
    ny = len(ys)

    nodes: List[Tuple[int, float, float]] = []
    for j in range(ny):
        for i in range(nx):
            nid = j * nx + i
            nodes.append((nid, float(xs[i]), float(ys[j])))

    elements_by_layer: dict = {}
    for j in range(ny - 1):
        layer = []
        for i in range(nx - 1):
            n1 = j * nx + i
            n2 = n1 + 1
            n3 = n1 + nx + 1
            n4 = n1 + nx
            eid = j * (nx - 1) + i
            layer.append((eid, n1, n2, n3, n4))
        elements_by_layer[j] = layer

    return nodes, elements_by_layer, nx


def generate():
    nodes, elements_by_layer, nx = _mesh()

    lines: List[str] = []
    _w = lines.append

    _w("**")
    _w("** ex03_display_fold.inp — Auto-generated by gen_ex03_inp.py")
    _w("** 7-layer Display Panel: PET (J2) + PSA (Linear Viscoelastic)")
    _w("** Hinge rotation driven via *RIGID BODY + *BOUNDARY")
    _w("**")
    _w("*HEADING")
    _w("DISPLAY PANEL FOLDING ANALYSIS (ex03)")
    _w("**")

    # ---- Nodes ----
    _w("*NODE")
    for nid, x, y in nodes:
        _w(f"{nid}, {x:.6f}, {y:.6f}")
    _w("99999, -15.0, -5.0")
    _w("99998,  15.0, -5.0")
    _w("**")

    # ---- Elements per layer ----
    layer_names = ["PET_0", "PSA_1", "PET_2", "PSA_3", "PET_4", "PSA_5", "PET_6"]
    for j, name in enumerate(layer_names):
        elems = elements_by_layer[j]
        _w(f"*ELEMENT, TYPE=CPE4, ELSET={name}")
        for eid, n1, n2, n3, n4 in elems:
            _w(f"{eid}, {n1}, {n2}, {n3}, {n4}")
        _w("**")

    # ---- Materials (hierarchical via *MATERIAL) ----
    _w("*MATERIAL, NAME=PET")
    _w("*ELASTIC")
    _w("4000.0, 0.3")
    _w("*PLASTIC")
    _w("80.0, 0.0")
    _w("700.0, 1.0")
    _w("**")

    _w("*MATERIAL, NAME=PSA")
    _w("*ELASTIC")
    _w("10.0, 0.49")
    _w("*VISCOELASTIC, TIME=PRONY")
    _w("0.8, 0.0, 1.0")
    _w("**")

    # ---- Solid Sections (pid assignment) ----
    _w("*SOLID SECTION, ELSET=PET_0, MATERIAL=PET")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PSA_1, MATERIAL=PSA")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PET_2, MATERIAL=PET")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PSA_3, MATERIAL=PSA")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PET_4, MATERIAL=PET")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PSA_5, MATERIAL=PSA")
    _w("0.05,")
    _w("*SOLID SECTION, ELSET=PET_6, MATERIAL=PET")
    _w("0.05,")
    _w("**")

    # ---- Node sets for hinge constraints ----
    _w("*NSET, NSET=HINGE_L_SLAVES")
    _w("0,")
    _w("*NSET, NSET=HINGE_R_SLAVES")
    _w(f"{nx - 1},")
    _w("**")

    # ---- RIGID BODY constraints ----
    _w("*RIGID BODY, NSET=HINGE_L_SLAVES, REF NODE=99999")
    _w("*RIGID BODY, NSET=HINGE_R_SLAVES, REF NODE=99998")
    _w("**")

    # ---- Contact surfaces (reference only — custom JAX penalty contact) ----
    top_start = max(0, (len(nodes) // 8 - 1) * nx)
    _w("*SURFACE, NAME=TOP_SURF, TYPE=NODE")
    _w(f"{top_start}, {top_start + nx - 1}")
    _w("*SURFACE, NAME=BOT_SURF, TYPE=NODE")
    _w(f"0, {nx - 1}")
    _w("*CONTACT PAIR, INTERACTION=FRICTIONLESS")
    _w("TOP_SURF, BOT_SURF")
    _w("**")

    # ---- Step ----
    _w("*STEP, NLGEOM=YES")
    _w("*STATIC")
    _w("0.02, 1.0, 1e-5, 0.05")
    _w("**")
    _w("*BOUNDARY")
    _w("99999, 1, 2, 0.0")
    _w("*BOUNDARY")
    _w("99998, 1, 2, 0.0")
    _w("**")
    _w("*END STEP")

    return "\n".join(lines)


if __name__ == "__main__":
    content = generate()
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated: {OUTPUT}")
    print(f"  {len(content.splitlines())} lines")
